# Sigmond Configuration
[build]
skip_query = false
skip_batch = false
precision = "double"
numbers = "complex"
default_file_format = "hdf5"
enable_minuit = false
enable_grace = true
verbose = false
build_jobs = 0             # Number of parallel build jobs (0 = auto-detect)
batch_install_dir = "/home/john/miniconda3/envs/spectrum/bin"     # Custom install directory for sigmond_batch (empty = default bin/)
query_install_dir = "/home/john/miniconda3/envs/spectrum/bin"     # Custom install directory for sigmond_query (empty = default bin/)

[libraries]
# Manual library paths (only specify if auto-detection fails)

[libraries.hdf5]
root_dir = ""              # Directory containing /include and /lib subdirectories
                           # with HDF5 headers and libraries
                    
[libraries.blas]
library_path = ""          # Path to BLAS .so/dylib file (e.g. libopenblas.so)

[libraries.lapack]
library_path = ""          # Path to LAPACK .so/dylib file (e.g. libopenblas.so)

[libraries.accelerate]
framework_dir = ""

[libraries.minuit2]
include_dir = ""            # e.g. /usr/include
library_dir = ""            # e.g. /usr/lib

[libraries.grace]
include_dir = "/usr/local/grace/include"
library_dir = "/usr/local/grace/lib"

[compiler]
cxx_flags = []
